[general]
output_file_path = "../src/API.jl"
smart_de_anonymize = true
use_deterministic_symbol = true
output_ignorelist = [
    "Steinberg_int8",
    "Steinberg_uint32",
    "char16_t",
    "Steinberg_uint8",
    "Steinberg_uchar",
    "Steinberg_int16",
    "Steinberg_uint16",
    "Steinberg_int32",
    "Steinberg_int64",
    "Steinberg_uint64",
    "Steinberg_TSize",
    "Steinberg_tresult",
    "Steinberg_TPtrInt",
    "Steinberg_TBool",
    "Steinberg_char8",
    "Steinberg_char16",
    "Steinberg_tchar",
    "Steinberg_CStringA",
    "Steinberg_CStringW",
    "Steinberg_CString",
    "Steinberg_FIDString",
    "Steinberg_UCoord",
    "Steinberg_LARGE_INT",
    "Steinberg_TUID",
    "Steinberg_Vst_TChar",
    "Steinberg_Vst_CString",
    "Steinberg_Vst_String128",
    "Steinberg_Vst_Sample32",
    "Steinberg_Vst_Sample64",
    "Steinberg_Vst_SampleRate",
    "Steinberg_Vst_NoteExpressionValue",
    "Steinberg_Vst_ParamValue",
    "Steinberg_Linux_TimerInterval",
    "Steinberg_Linux_ITimerHandler",
    "Steinberg_Linux_ITimerHandlerVtbl",
    "Steinberg_Linux_IEventHandler",
    "Steinberg_Linux_IEventHandlerVtbl",
    "Steinberg_Linux_IRunLoop",
    "Steinberg_Linux_IRunLoopVtbl",
    "Steinberg_Linux_FileDescriptor",
    "Steinberg_Vst_IContextMenu_Item",
    "Steinberg_Vst_MediaType",
    "Steinberg_Vst_BusDirection",
    "Steinberg_Vst_BusType",
    "Steinberg_Vst_IoMode",
    "Steinberg_Vst_NoteExpressionTypeID",
    "Steinberg_Vst_KeyswitchTypeID",
    "Steinberg_Vst_PhysicalUITypeID",
    "Steinberg_Vst_KnobMode",
    "Steinberg_Vst_PrefetchableSupport",
]
struct_field_count_assert = false

[codegen]
use_julia_bool = true
always_NUL_terminated_string = true
